In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2021-09-13 09:17:11--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.02s   

2021-09-13 09:17:11 (58.3 MB/s) - ‘data.csv’ saved [1475504/1475504]



In [6]:
df = pd.read_csv('data.csv')
len(df)

11914

In [9]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [7]:
df.head()

Make       Model  Year  ... city mpg  Popularity   MSRP
0  BMW  1 Series M  2011  ...       19        3916  46135
1  BMW    1 Series  2011  ...       19        3916  40650
2  BMW    1 Series  2011  ...       20        3916  36350
3  BMW    1 Series  2011  ...       18        3916  29450
4  BMW    1 Series  2011  ...       18        3916  34500

[5 rows x 16 columns]

In [10]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

string_columns = list(df.dtypes[df.dtypes == 'object'].index)

for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [11]:
df.head()

make       model  year  ... city_mpg  popularity   msrp
0  bmw  1_series_m  2011  ...       19        3916  46135
1  bmw    1_series  2011  ...       19        3916  40650
2  bmw    1_series  2011  ...       20        3916  36350
3  bmw    1_series  2011  ...       18        3916  29450
4  bmw    1_series  2011  ...       18        3916  34500

[5 rows x 16 columns]

In [ ]:
# q1

In [2]:
np.__version__

'1.19.5'

In [ ]:
# q2

In [3]:
pd.__version__

'1.1.5'

In [ ]:
# q3

In [19]:
df[df['make']=='bmw']['msrp'].mean()

61546.76347305389

In [ ]:
# q4

In [72]:
df[df['year']>=2015]['engine_hp'].isnull().sum()

51

In [ ]:
# q5

In [29]:
mean_hp_before = round(df['engine_hp'].mean())
mean_hp_before

249

In [31]:
mean_hp_after = round(df['engine_hp'].fillna(mean_hp_before).mean())
mean_hp_after

249

In [41]:
# q6

In [42]:
X = df[df['make']=='rolls-royce'][["engine_hp", "engine_cylinders", "highway_mpg"]].drop_duplicates()
X

engine_hp  engine_cylinders  highway_mpg
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [50]:
XTX = np.dot(X.values.T, X.values)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [53]:
XTX = np.matmul(X.values.T, X.values)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [60]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [61]:
inv_XTX.sum()

0.032212320677486125

In [ ]:
# q7

In [63]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [68]:
w = np.matmul(np.matmul(inv_XTX,X.values.T), y)
w[0]

0.19989598183188978